- name: Create Database
  command: /usr/edb/as{{pgversion}}/bin/edb-as-{{pgversion}}-setup initdb
  args:
    creates: /var/lib/edb/as{{pgversion}}/data/base
  become: yes

- name: Start Database
  service:
    name: edb-as-{{pgversion}}
    enabled: yes
    state: started
