
# mainly for the GPGKEY. The repositoryfile will be replace with
# a templatefile!
- name: Install YUM Repositories with GPGKEY
  yum:
    name: "https://yum.enterprisedb.com/edbrepos/edb-repo-latest.noarch.rpm"
    state: latest

- name: Configure YUM-Repositories
  replace:
    path: /etc/yum.repos.d/edb.repo
    regexp: '<username>:<password>'
    replace: '{{yumuser}}:{{yumpassword}}'
    backup: yes
    mode: 0600
  tags: passwd

- name: Install RPMs
  yum: 
    name: ["edb-as{{pgversion}}-server", "bash-completion"]
    state: latest
